### ISSUE TITLE
Add service status warning / critical / passing to labels

### ISSUE THREAD

**Issue by nickvth** [prometheus/consul_exporter#46]
So i can make graphs and alerts for warning or critical state.

**Comment by nickvth** [comment]
https://github.com/prometheus/consul_exporter/pull/51

**Comment by grobie** [comment]
I can see the need to detect checks in warning state. Looking at the implementation attempt in #51, here some comments and requirements.

* It doesn't make sense to attach a `status` label to the `catalog_service_node_healthy` metric, as its name and description clearly indicate to return a boolean 1/0 value. We could rename the metric, but given we already have metrics for every single check, I'd just leave that metric and not break compatibility.
* In Prometheus we expose states either as boolean 1/0 values or by using something like a `status` label with static value of 1. #51 now mixes both approaches leading to the confusing result of having a value of 1 for status=warning/critical series and a value of 0 for status=passing one. If we switch to status labels we have to adjust the value.
* Due issues with the detection of stale (not longer present) time series, it's an anti-pattern to stop exporting some time series, e.g. when switching from one check state to another. The correct way is to always export time series for all states, where only the currently active one uses a value of 1, all other a value of 0. The current implementation in #51 will cause issues to detect a state change correctly due to Prometheus' current staleness handling.

**Comment by grobie** [comment]
Fixed in #53.
